### PR TITLE
Add pgraphs to apps.md

### PR DESCRIPTION
**Pull request by nichtich**
pgraphs is a graph format converter. See https://www.npmjs.com/package/pgraphs#json-canvas for usage example with JSON Canvas.

### CODE REVIEW

**Comment by kepano** [comment]
Thanks for your contribution! From what I can see I would not consider this to be a standalone app . It seems like this would be a better fit for the tools category.

**Comment by nichtich** [comment]
The distinction between "app" and "tool" is not obvious and showing capabilities of each would be nice, so how about merging them? I've updated my pull request, please have a look!

**Comment by kepano** [comment]
I do not think we should merge them. The distinction is that apps have a GUI for manipulating infinite canvases.

**Comment by nichtich** [comment]
> The distinction is that apps have a GUI for manipulating infinite canvases

So pure viewers without methods to drag around nodes are not apps but tools? Or is the main feature of app having a GUI with infinite canvases and manipulating is just a bonus? Sorry for being puzzled. I've tried to change the introduction sentence for clarification in my branch. Don't hesitate to further comment or directly modify the page.

**Comment by kepano** [comment]
I think the description changes are making things less clear. I have added pgraphs to apps.md in a separate commit.

**Pull request closed without merging**
